MBTIAPP/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = 'MBTIAPP'

urlpatterns = [
    path('', views.main, name='main'),
    path('login/', auth_views.LoginView.as_view(template_name='MBTIAPP/login.html'),name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('signup/', views.signup, name='signup'),
    path('mbtitest/', views.mbtitest, name='mbtitest'),
    path('result/', views.result, name='result'),
    path('blog/', views.blog, name='blog'),
    path('category/<int:category_id>/', views.category, name='category'),
    path('my_posts/', views.my_posts, name='my_posts'),
    path('user_post/<int:poster_id>/', views.user_post, name='user_post'),
    path('new/', views.new, name='new'),
    path('postcreate/', views.postcreate, name='postcreate'),
    path('<int:pk>/', views.detail, name='detail'),
    path('<int:pk>/edit/', views.edit, name='edit'),
    path('<int:pk>/delete/', views.delete, name='delete'),
    path('<int:pk>/comment/', views.comment_create, name='comment_create'),
    path('<int:post_pk>/comment/<int:comment_pk>/delete/', views.comment_delete, name='comment_delete'),
    path('<int:post_pk>/comment/<int:comment_pk>/edit/', views.comment_edit, name='comment_edit'),
]
    

MBTI_likelion/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('mbti/', include('MBTIAPP.urls')),
    path('admin/', admin.site.urls),
]

MBTIAPP/models.py
from django.conf import settings
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.contrib.auth.models import User

#아이디 / 비밀번호 / 닉네임 / MBTI / 회원가입 / 

# Create your models here.

#회원가입

class Profile(AbstractUser):
    nickname = models.CharField(max_length=15);
    user_mbti = models.CharField(max_length=4);

    def __str__(self):
        return self.nickname
    
class Category(models.Model):
    name = models.CharField(max_length=30)

    def __str__(self):
        return self.name

    
class Post(models.Model):
    title =models.CharField(max_length=50)
    poster = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE ,default=1)
    content = models.TextField()
    categories = models.ManyToManyField(Category)


    
    def __str__(self):
        return self.title
    
class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    commenter = models.ForeignKey(settings.AUTH_USER_MODEL , on_delete=models.CASCADE)
    content = models.CharField(max_length=150)

    def __str__(self):
        return self.content

MBTIAPP/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from MBTIAPP.models import Profile, Comment
from django.contrib.auth.models import User

class Signupform(UserCreationForm):
    nickname = forms.CharField(max_length=15 ,label="닉네임", required=True)

    class Meta:
        model = Profile
        fields = ("username", "password1" , "password2", "nickname")


class MbtiForm(forms.Form):
    EI = forms.ChoiceField(choices=[('E','네'),('I','아니오')], widget=forms.RadioSelect)
    NS = forms.ChoiceField(choices=[('N','네'),('S','아니오')], widget=forms.RadioSelect)
    TF = forms.ChoiceField(choices=[('F','네'),('T','아니오')], widget=forms.RadioSelect)
    PJ = forms.ChoiceField(choices=[('J','네'),('P','아니오')], widget=forms.RadioSelect)

class CommentForm(forms.ModelForm):

    class Meta:
        model = Comment
        exclude = ('post','commenter')

MBTIAPP/views.py
from rest_framework.response import Response
from .serializers import PostSerializer, CommentSerializer
from django.shortcuts import render, get_object_or_404
from django.contrib.auth import authenticate, login
from django.shortcuts import redirect
from MBTIAPP.forms import Signupform,MbtiForm,CommentForm
from .models import Post, Profile, Comment, Category
from rest_framework.decorators import api_view
# from django.urls import reverse


# Create your views here.
def main(request):
    
    return render(request, 'MBTIAPP/main.html')

def detail(request, pk):
    post_detail = get_object_or_404(Post, pk=pk)
    comments = post_detail.comment_set.all()
    context = {
        'post' : post_detail,
        'comments' : comments,
    }
    return render(request, 'MBTIAPP/detail.html', context)

def edit(request, pk):
    post = Post.objects.get(pk=pk)
    if request.method == 'POST':
        post.title=request.POST['title']
        post.content=request.POST['content']
        post.save()  
        return redirect('MBTIAPP:detail', pk)
    else:
        context = {
            'post' : post
        }
        return render(request, 'MBTIAPP/edit.html', context), render(request, 'MBTIAPP/blog.html', context)
    
def delete(pk):
    post = Post.objects.get(pk=pk)
    post.delete()
    return redirect('MBTIAPP:blog')

def blog(request):
    posts = Post.objects.all()
    category = Category.objects.all()
    context = {
        'posts':posts,
        'category':category
        }
    return render(request, 'MBTIAPP/blog.html', context)


@api_view(['GET'])
def category(request, category_id):
    posts = Post.objects.filter(categories=category_id)
    serializer = PostSerializer(posts, many=True)
    return Response(serializer.data)

@api_view(['GET'])
def my_posts(requsest):
    user_id=requsest.user.id
    posts = Post.objects.filter(poster=user_id)
    serializer = PostSerializer(posts, many=True)
    serialized_data= serializer.data
    return Response(serialized_data)

@api_view(['GET'])
def user_post(request, poster_id):
    posts =  Post.objects.filter(poster = poster_id)
    serializer = PostSerializer(posts, many=True)
    return Response(serializer.data)

@api_view(['GET'])
def get_my_comments(request):
    user_id = request.user.id
    comments = Comment.objects.filter(poster = user_id)
    serializer = CommentSerializer(comments, many=True)
    return Response(serializer.data)

def new(request):
    categories = Category.objects.all()
    context = {
        'categories' : categories
    }
    return render(request, 'MBTIAPP/postcreate.html', context)

def postcreate(request):
    if(request.method == 'POST'):
        post = Post()
        post.title=request.POST['title']
        post.content=request.POST['content']
        post.poster = request.user
        post.save()     
        categories = request.POST.getlist('category')
        if categories: 
            post.categories.set(categories)
    return redirect('MBTIAPP:blog')


def comment_create(request, pk):
    if request.user.is_authenticated:
        post = get_object_or_404(Post, pk=pk)
        form = CommentForm()
        if request.method == 'POST':
            comment_form = CommentForm(request.POST)
            if comment_form.is_valid():
                comment = comment_form.save(commit=False)
                comment.post = post
                comment.commenter = request.user
                comment.save()
                return redirect('MBTIAPP:detail', pk)
        else:
            form = CommentForm()
        return render(request, 'MBTIAPP/detail.html', {'post':post, 'form': form})



def comment_delete(request, post_pk, comment_pk):
    if request.user.is_authenticated:
        comment = get_object_or_404(Comment, pk=comment_pk)
        if request.user == comment.commenter:
            comment.delete()
    return redirect('MBTIAPP:detail', post_pk) 

def comment_edit(request, post_pk, comment_pk):
    post = get_object_or_404(Post, pk=post_pk)
    comment = Comment.objects.get(pk=comment_pk)
    if request.method == 'POST':
            comment.content=request.POST['content']
            comment.save()  
            return redirect('MBTIAPP:detail', post_pk)
    else:
        context = {
            'comment' : comment,
            'post' : post,
            'comment_content' : comment.content
        }
        return render(request, 'MBTIAPP/comment_edit.html', context)   

def mbtitest(request):
    form = MbtiForm()
    return render(request, 'MBTIAPP/mbti_test.html', {'form':form})

def result(request):
    if request.method == 'POST':
        form = MbtiForm(request.POST)
        if form.is_valid():
            EI = form.cleaned_data['EI']
            NS = form.cleaned_data['NS']
            TF = form.cleaned_data['TF']
            PJ = form.cleaned_data['PJ']
            arr=[EI, NS, TF, PJ]
            my_mbti = ''.join(arr)
            user = request.user
            user.user_mbti = my_mbti
            user.save()
            context = {'mymbti':my_mbti}
            return render(request, 'MBTIAPP/result.html', context)
    else:
        form = MbtiForm()
        context = {'form': form}
        return render(request, 'MBTIAPP/result.html',context)





def signup(request):
    if request.method == "POST":
        form = Signupform(request.POST)
        if form.is_valid():
                form.save()
                username = form.cleaned_data.get('username')
                raw_password = form.cleaned_data.get('password1')
                user = authenticate(username=username, password=raw_password)
                login(request, user)
                return redirect('MBTIAPP:main')
    else:
        form = Signupform()
    return render(request, 'MBTIAPP/signup.html', {'form' : form})

MBTIAPP/templates/MBTIAPP/blog.html
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">

<a href="{% url 'MBTIAPP:new' %}">새 글쓰기</a><br><br>

{% if post.category.id %}
<form method="get" action="{% url 'MBTIAPP:category' category_id=post.category.id %}">
    <label for="category">카테고리</label>
    <select name="category">
        <option value="">전체</option>
        {% for category in categories %}
            <option value="{{ category.id }}">{{ category.name }}</option>
        {% endfor %}
    </select>
    <button type="submit">적용</button>
</form>
{% endif %}

<a href="{% url 'MBTIAPP:my_posts' %}">내가 쓴 글만 보기</a>



{% for post in posts %}
    <div class="posts">
        <h2>글 제목</h2>
        <a href="{% url 'MBTIAPP:detail' post.pk %}">{{post.title}}</a>
        <h2>작성자</h2>
        <p>{{post.poster.nickname}}<span>({{ post.poster.user_mbti }})</span></p>
        <h2>카테고리</h2>
        <p>
            {% for category in post.categories.all %}
                {{ category.name }}
            {% endfor %}

        </p>
    </div> 
{% empty %}  
    <p>해당 게시글이 존재하지 않습니다.</p>
{% endfor %}

MBTIAPP/templates/MBTIAPP/comment_edit.html
<h2>comment edit</h2>
<form action="{% url 'MBTIAPP:comment_edit' post.pk comment.pk %}" method="POST">
    {% csrf_token %}
    <h3>content</h3><br>
    <textarea name="content" id="content" cols="40" rows="20">{{ comment.content }}</textarea><br>
    <input type="submit" value="수정하기">
</form>

MBTIAPP/templates/MBTIAPP/detail.html
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">

<h1>디테일페이지</h1>
    <div class="details">
        <a href="{% url 'MBTIAPP:blog' %}">게시판으로 돌아가기</a><br>
        <h2>제목</h2>
        <p>{{ post.title }}</p>
        <h2>카테고리</h2>
        <h2>내용</h2>
        <p>{{ post.content }}</p>
        <h2>작성자</h2>
        <span>{{ post.poster }}({{ post.poster.user_mbti }})</span><br><br><br>
        {% if user == post.poster %}
        <a href="{% url 'MBTIAPP:edit' post.pk %}">수정하기</a>
        <a href="{% url 'MBTIAPP:delete' post.pk %}">삭제하기</a>
        {% endif %}
    </div>

<h3>댓글들</h3>
{% if comments %}
<p>{{ comments|length }}개의 댓글이 있어요</p>
{% endif %}
<ul>
    {% for comment in comments %}
    <li>
        {{ comment.content }} - {{ comment.commenter }}<span>({{ comment.commenter.user_mbti }})</span>
        {% if user == comment.commenter %}
            <form action="{% url 'MBTIAPP:comment_delete' post.pk comment.pk %}">
            {% csrf_token %}
            <br><div class="buttons"><input type="submit" value="댓글삭제">
            </div>
            </form>
            <a href="{% url 'MBTIAPP:comment_edit' post.pk comment.pk %}">수정하기</a>
        {% endif %}
    </li>
    {% empty %}
        <p>No 댓글~</p>
    {% endfor %}
</ul>

{% if request.user.is_authenticated %}
    <form action="{% url 'MBTIAPP:comment_create' pk=post.pk %}" method="POST">
        {% csrf_token %}
        {{ form.content }}
        <div class="buttons">
        <input type="submit" value ="댓글작성">
        </div>
    </form>
{% else %}
    <a href="{% url 'MBTIAPP:login' %}">댓글을 작성하고 싶으면 로그인하시오.</a>
{% endif %}

MBTIAPP/templates/MBTIAPP/edit.html
<h2>edit</h2>
<form action="{% url 'MBTIAPP:edit' post.pk %}" method="POST">
    {% csrf_token %}
    <h3>Title</h3><br>
    <input type="text" name="title" value="{{ post.title }}"><br>
    <h3>content</h3><br>
    <textarea name="content" id="content" cols="40" rows="20">{{ post.content }}</textarea><br>
    <input type="submit" value="수정하기">
</form>

MBTIAPP/templates/MBTIAPP/form_errors.html
{% if form.errors %}
    {% for field in form %}
        {% if field.errors %}
            <strong>{{ field.label }}</strong>
            {{ field.errors }}
        {% endif %}
    {% endfor %}
    {% for error in form.non_field_errors %}
    <div>
        <strong>{{ error }}</strong>
    </div>
    {% endfor %}
</div>
{% endif %}

MBTIAPP/templates/MBTIAPP/login.html
<h1>로그인하세요.</h1>
<form method="post" action="{% url 'MBTIAPP:login' %}">
    {% csrf_token %}
    {% include "MBTIAPP/form_errors.html" %}
    <label>ID</label>
    <input type="text" name="username" id="username">
    <label>PW</label>
    <input type="text" name="password" id="password">
    <button type="submit">로그인</button>
</form>

MBTIAPP/templates/MBTIAPP/main.html
{% if user.is_authenticated %}
{% csrf_token %}
<a href="{% url 'MBTIAPP:logout' %}">로그아웃</a>
<a href="{% url 'MBTIAPP:mbtitest' %}">MBTI테스트 하기</a>
<a href="{% url 'MBTIAPP:blog' %}">MBTI 게시판으로</a>
{% endif %}

{% if not user.is_authenticated %}
{% csrf_token %}
<a href="{% url 'MBTIAPP:login' %}">로그인</a>
<a href="{% url 'MBTIAPP:signup' %}">회원가입</a>
{% endif %}

MBTIAPP/templates/MBTIAPP/mbti_test.html
<h1>MBTI TEST</h1>
<form action="{% url 'MBTIAPP:result' %}" method="post">
{% csrf_token %}
<p>나는 사람들과 같이 있을 때 에너지를 얻는다.</p>
{{ form.EI }}<br>

<p>나는 상상을 자주 하는 편이다.</p>
{{ form.NS }}<br>

<p>나는 남의 이야기에 공감을 잘 하는 편이다.</p>
{{ form.TF }}<br>

<p>나는 행동을 하기전에 계획을 먼저 세우는 편이다.</p>
{{ form.PJ }}<br>

<input type="submit" value="검사 결과 확인하기">



</form>

MBTIAPP/templates/MBTIAPP/postcreate.html
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">

<h1>새글 작성페이지</h1>
<a href="{% url 'MBTIAPP:blog' %}">게시판으로 돌아가기</a><br><br>

<form action="{% url 'MBTIAPP:postcreate' %}" method="POST">
    {% csrf_token %}
    <label for="title">제목</label><br>
    <input type="text" name="title", id="title"><br>
    <label for="content">글 내용</label><br>
    <textarea name="content" id="content" cols="40" rows="20"></textarea><br>
    <label for="category">카테고리</label>
    <select name="category" multiple>
    {% for category in categories %}
        <option value="{{ category.id }}">{{ category.name }}</option>
    {% endfor %}
    </select>
    <button type="submit">작성</button>
</form>

MBTIAPP/templates/MBTIAPP/result.html
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">
<h1>결과창임</h1>
{{ mymbti }}
<a href="{% url 'MBTIAPP:blog' %}">mbti 게시판으로 이동하기</a>

MBTIAPP/templates/MBTIAPP/signup.html
<h1>회원가입</h1>

<form method="post" action="{% url 'MBTIAPP:signup' %}">
    {% csrf_token %}
    {% include "MBTIAPP/form_errors.html" %}
    <label for="username">사용자 이름</label><br>
    <input type="text" name="username" value="{{ form.username.value|default_if_none:'' }}">
    <br><br>
    <label for="password1">비밀번호</label><br>
    <input type="password" name="password1" value="{{ form.password1.value|default_if_none:'' }}">
    <br><br>
    <label for="username">비밀번호 확인</label><br>
    <input type="password" name="password2" value="{{ form.password2.value|default_if_none:'' }}">
    <br><br>
    <label for="nickname">닉네임</label><br>
    <input type="text" class="form-control" name="nickname" value="{{ form.nickname.value|default_if_none:'' }}">
    <br><br>
    <button type="submit">생성</button>
</form>